language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements/develop.txt"
# command to run tests
script:
  - pep8
notifications:
  slack: seungkwondev:Yiqb8EFJyIYqrsYZ1wkyHati
